apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app : {{ .Values.ui.name }}
  name: {{ .Values.ui.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas.ui }}
  selector:
    matchLabels:
      app: {{ .Values.ui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ui.name }}
      annotations:
        rollingupdate: {{ randAlphaNum 5 | quote}} # Redeploy on every 'helm upgrade'
    spec:
      restartPolicy: Always
      volumes:
        - name: medifor-data
          persistentVolumeClaim:
            claimName: medifor-data-pvc
      containers:
      - name: ui
        image: {{ .Values.ui.container }}
        {{- if not .Values.remotedeploy }}
        imagePullPolicy: Always
        {{- end }}
        ports:
          - containerPort: {{ .Values.ui.port }}
            name: http
        env:
          {{- range $key, $value := .Values.ui.env }}
          {{- if not (deepEqual $value "") }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
          {{- end }}
          {{- end }}
        volumeMounts:
          - name: medifor-data
            mountPath: {{ .Values.ui.env.CONTAINER_ROOT}}
        resources:
          limits:
            cpu: 1.0
            memory: 1Gi
            nvidia.com/gpu: 0
          requests:
            cpu: 100m
            memory: 250Mi
            nvidia.com/gpu: 0