apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: {{ .Values.ui.name }}
  name: {{ .Values.ui.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.ui.port }}
      protocol: TCP
      targetPort: {{ .Values.ui.port }}
  selector:
    app: {{ .Values.ui.name }}
