{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels: 
    k8s-app: eqmedifor-metrics-monitor
    release: prometheus
  name: eqmedifor-metrics-monitor
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: eqmedifor-service
  endpoints:
  - port: prometheus
    path: /metrics
    interval: 15s
{{ end }}