apiVersion: v1
kind: Service
metadata:
  labels:
    app: eqmedifor-service
  name: eqmedifor
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.entroq.ports.grpc }}
      protocol: TCP
      targetPort: {{ .Values.entroq.ports.grpc }}
    {{- if .Values.prometheus.enabled }}
    - name: prometheus
      port: {{ .Values.entroq.ports.metrics }}
      protocol: TCP
      targetPort: prometheus
    {{- end }}
  selector:
    app: eqmedifor
