apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: analyticscaler
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  verbs:
  - get
  - update
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/status
  - deployments/scale
  verbs:
  - get
  - update
  - list
  - watch
