apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: init-privileged
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
