apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: run-as-any
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - run-as-any
  resources:
  - podsecuritypolicies
  verbs:
  - use
