apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: init-privileged
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: init-privileged
subjects:
- kind: ServiceAccount
  name: init-privileged
  namespace: {{ .Values.namespace }}
