apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: analytic-run-as-any
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: run-as-any
subjects:
- kind: ServiceAccount
  name: analytic
  namespace: {{ .Values.namespace }}
