apiVersion: v1
kind: ConfigMap
metadata:
  name: eqmedifor-pgsql-init-script
  namespace: {{ .Values.namespace }}
data:
  data.sql: |
    CREATE DATABASE entroq;
  user.conf: |
    max_connections=500
