apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgmedifor
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  serviceName: pgmedifor
  selector:
    matchLabels:
      app: pgmedifor
  template:
    metadata:
      labels:
        app: pgmedifor
    spec:
      containers:
      - image: "postgres:11"
        name: pgmedifor
        env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: PGDATA
            value: /var/lib/postgresql/data
        ports:
        - containerPort: {{ .Values.postgres.port }}
        volumeMounts:
        - name: postgres-data
          subPath: postgres
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

