apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: autoretain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
