apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: medifor-data
  name: medifor-data-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistentvolume.requests }}
  selector:
    matchLabels:
      type: local
      vol: medifor-data
