apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: medifor-data
  name: medifor-data-pvc
  namespace: {{ .Values.namespace }}
spec:
  {{- if .Values.persistence.medifor.storageClass }}
  storageClassName: {{ .Values.persistence.medifor.storageClass }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.medifor.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.medifor.size }}
  
