apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Values.namespace }}
spec:
  {{- if .Values.persistence.postgres.storageClass }}
  storageClassName: {{ .Values.perssistence.postgres.storageClass }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.postgres.accessMode | quote}}
  resources:
    requests:
      storage: {{ .Values.persistence.postgres.size }}
 
